import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

// const plus_jakarta_sans = Plus_Jakarta_Sans({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={plus_jakarta_sans.className}>{children}</body>
//     </html>
//   );
// }

// app/layout.tsx

import React from 'react';
import NavBar from './components/NavBar'; 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex">
        <NavBar/>
        <main className="flex-grow p-4">{children}</main>
      </body>
    </html>
  );
}
